[16/May/2017 09:59:20] DEBUG [django.db.backends:89] (0.012) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[16/May/2017 09:59:20] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[16/May/2017 10:00:44] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[16/May/2017 10:00:44] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[16/May/2017 10:01:04] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/Catalogues HTTP/1.1" 200 3857
[16/May/2017 10:01:04] INFO [django.server:124] "GET /static/portailCRC/css/home.css HTTP/1.1" 200 480
[16/May/2017 10:01:04] INFO [django.server:124] "GET /static/portailCRC/images/logo_biogeo_72.jpg HTTP/1.1" 200 15505
[16/May/2017 10:01:04] INFO [django.server:124] "GET /static/portailCRC/images/bandeau-labo4.jpg HTTP/1.1" 200 16156
[16/May/2017 10:01:04] INFO [django.server:124] "GET /static/portailCRC/images/Logo_CRC_transparent.png HTTP/1.1" 200 13653
[16/May/2017 10:01:05] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[16/May/2017 10:01:05] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'portailCRC.urls' from '/home/mers/dev/crc/portailCRC/urls.pyc'> (portailCRC:portailCRC) ^climdata.u-bourgogne.fr/Catalogues>"
[16/May/2017 10:01:05] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'teledm.urls' from '/home/mers/dev/crc/teledm/urls.pyc'> (teledm:teledm) ^climdata.u-bourgogne.fr/teledm/>"
[16/May/2017 10:01:05] WARNING [django.request:152] Not Found: /favicon.ico
[16/May/2017 10:01:05] WARNING [django.server:124] "GET /favicon.ico HTTP/1.1" 404 3336
[16/May/2017 10:01:05] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[16/May/2017 10:01:05] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'portailCRC.urls' from '/home/mers/dev/crc/portailCRC/urls.pyc'> (portailCRC:portailCRC) ^climdata.u-bourgogne.fr/Catalogues>"
[16/May/2017 10:01:05] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'teledm.urls' from '/home/mers/dev/crc/teledm/urls.pyc'> (teledm:teledm) ^climdata.u-bourgogne.fr/teledm/>"
[16/May/2017 10:01:05] WARNING [django.request:152] Not Found: /favicon.ico
[16/May/2017 10:01:05] WARNING [django.server:124] "GET /favicon.ico HTTP/1.1" 404 3336
[16/May/2017 10:01:06] DEBUG [teledm.views:140] this is a debug message!
[16/May/2017 10:01:06] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 141, in home
    return render_to_response('teledm/home.html', context_instance=RequestContext(request))
TypeError: render_to_response() got an unexpected keyword argument 'context_instance'
[16/May/2017 10:01:06] ERROR [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/ HTTP/1.1" 500 92236
[16/May/2017 10:03:30] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[16/May/2017 10:03:30] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[16/May/2017 10:04:10] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[16/May/2017 10:04:10] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[16/May/2017 10:05:54] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[16/May/2017 10:05:54] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[16/May/2017 10:10:20] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[16/May/2017 10:10:20] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[16/May/2017 10:10:39] DEBUG [django.db.backends:91] (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[16/May/2017 10:10:39] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[16/May/2017 10:10:52] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[16/May/2017 10:10:52] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[16/May/2017 10:10:59] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/Catalogues HTTP/1.1" 200 3857
[16/May/2017 10:11:01] DEBUG [teledm.views:140] this is a debug message!
[16/May/2017 10:11:01] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/ HTTP/1.1" 200 8882
[16/May/2017 10:11:01] INFO [django.server:124] "GET /static/teledm/css/base.css HTTP/1.1" 200 859
[16/May/2017 10:11:01] INFO [django.server:124] "GET /static/teledm/css/form.css HTTP/1.1" 200 2271
[16/May/2017 10:11:01] INFO [django.server:124] "GET /static/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 200 121200
[16/May/2017 10:11:01] INFO [django.server:124] "GET /static/jquery-ui/jquery-ui.js HTTP/1.1" 200 520714
[16/May/2017 10:11:01] INFO [django.server:124] "GET /static/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 200 37045
[16/May/2017 10:11:02] INFO [django.server:124] "GET /static/jquery/dist/jquery.js HTTP/1.1" 200 267194
[16/May/2017 10:11:02] INFO [django.server:124] "GET /static/jquery.cookie/jquery.cookie.js HTTP/1.1" 200 3121
[16/May/2017 10:11:02] INFO [django.server:124] "GET /static/moment/min/moment.min.js HTTP/1.1" 200 61317
[16/May/2017 10:11:02] INFO [django.server:124] "GET /static/select2/dist/css/select2.min.css HTTP/1.1" 200 15196
[16/May/2017 10:11:02] INFO [django.server:124] "GET /static/teledm/js/base.js HTTP/1.1" 200 129
[16/May/2017 10:11:02] INFO [django.server:124] "GET /static/teledm/js/home.js HTTP/1.1" 200 364
[16/May/2017 10:11:02] INFO [django.server:124] "GET /static/select2/dist/js/select2.js HTTP/1.1" 200 141934
[16/May/2017 10:11:02] INFO [django.server:124] "GET /static/teledm/images/institutPasteur.jpeg HTTP/1.1" 200 3518
[16/May/2017 10:11:02] INFO [django.server:124] "GET /static/teledm/images/ehesp.jpeg HTTP/1.1" 200 1833
[16/May/2017 10:11:02] INFO [django.server:124] "GET /static/teledm/images/cnrs.jpeg HTTP/1.1" 200 2330
[16/May/2017 10:11:02] INFO [django.server:124] "GET /static/teledm/images/cnrm.jpeg HTTP/1.1" 200 6949
[16/May/2017 10:11:02] INFO [django.server:124] "GET /static/teledm/images/crc.jpeg HTTP/1.1" 200 2522
[16/May/2017 10:11:02] INFO [django.server:124] "GET /static/teledm/images/ird.jpeg HTTP/1.1" 200 5127
[16/May/2017 10:11:02] INFO [django.server:124] "GET /static/teledm/images/ub.jpeg HTTP/1.1" 200 3992
[16/May/2017 10:11:02] INFO [django.server:124] "GET /static/teledm/images/uLille1.jpeg HTTP/1.1" 200 2347
[16/May/2017 10:11:02] INFO [django.server:124] "GET /static/teledm/images/ulg.jpeg HTTP/1.1" 200 1587
[16/May/2017 10:11:02] INFO [django.server:124] "GET /static/teledm/images/image_en_tete.jpeg HTTP/1.1" 200 36924
[16/May/2017 10:11:04] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 62, in test
    wms = WebMapService(url, version='1.3.0')
  File "/home/mers/.local/lib/python2.7/site-packages/owslib/wms.py", line 51, in WebMapService
    timeout=timeout, headers=headers)
  File "/home/mers/.local/lib/python2.7/site-packages/owslib/map/wms130.py", line 73, in __init__
    self._capabilities = reader.read(self.url, timeout=self.timeout)
  File "/home/mers/.local/lib/python2.7/site-packages/owslib/map/common.py", line 71, in read
    headers=self.headers)
  File "/home/mers/.local/lib/python2.7/site-packages/owslib/util.py", line 183, in openURL
    **rkwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thredds/wms/satellite/modis/MYD04/res009/MYD04_r009_d.nc?service=WMS&request=GetCapabilities&version=1.3.0 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f4e54600450>: Failed to establish a new connection: [Errno 111] Connection refused',))
[16/May/2017 10:11:04] ERROR [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/test/ HTTP/1.1" 500 137371
[16/May/2017 10:11:21] DEBUG [teledm.views:193] Debug message!
[16/May/2017 10:11:21] INFO [teledm.views:194] Info message!
[16/May/2017 10:11:21] WARNING [teledm.views:195] Warning message!
[16/May/2017 10:11:21] ERROR [teledm.views:196] Error message!
[16/May/2017 10:11:21] CRITICAL [teledm.views:197] Critical message!
[16/May/2017 10:11:21] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 20280
[16/May/2017 10:11:21] INFO [django.server:124] "GET /static/teledm/css/mapViewer.css HTTP/1.1" 200 921
[16/May/2017 10:11:22] INFO [django.server:124] "GET /static/highcharts-export-csv/export-csv.js HTTP/1.1" 200 11927
[16/May/2017 10:11:22] INFO [django.server:124] "GET /static/teledm/js/mapViewer.js HTTP/1.1" 200 62092
[16/May/2017 10:11:22] INFO [django.server:124] "GET /static/html5shiv/dist/html5shiv-printshiv.js HTTP/1.1" 200 16268
[16/May/2017 10:11:22] INFO [django.server:124] "GET /static/respond/src/respond.js HTTP/1.1" 200 9754
[16/May/2017 10:11:22] INFO [django.server:124] "GET /static/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 18028
[16/May/2017 10:11:24] INFO [django.server:124] "GET /static/teledm/images/pan.png HTTP/1.1" 200 606
[16/May/2017 10:11:24] INFO [django.server:124] "GET /static/teledm/images/zoomIn.png HTTP/1.1" 200 975
[16/May/2017 10:11:24] INFO [django.server:124] "GET /static/teledm/images/info.png HTTP/1.1" 200 1010
[16/May/2017 10:11:34] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/Catalogues HTTP/1.1" 200 3857
[16/May/2017 10:11:35] DEBUG [teledm.views:140] this is a debug message!
[16/May/2017 10:11:35] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/ HTTP/1.1" 200 8882
[16/May/2017 10:11:37] ERROR [django.request:135] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 62, in test
    wms = WebMapService(url, version='1.3.0')
  File "/home/mers/.local/lib/python2.7/site-packages/owslib/wms.py", line 51, in WebMapService
    timeout=timeout, headers=headers)
  File "/home/mers/.local/lib/python2.7/site-packages/owslib/map/wms130.py", line 73, in __init__
    self._capabilities = reader.read(self.url, timeout=self.timeout)
  File "/home/mers/.local/lib/python2.7/site-packages/owslib/map/common.py", line 71, in read
    headers=self.headers)
  File "/home/mers/.local/lib/python2.7/site-packages/owslib/util.py", line 183, in openURL
    **rkwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thredds/wms/satellite/modis/MYD04/res009/MYD04_r009_d.nc?service=WMS&request=GetCapabilities&version=1.3.0 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f4e5463b3d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
[16/May/2017 10:11:37] ERROR [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/test/ HTTP/1.1" 500 138097
[16/May/2017 10:15:00] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[16/May/2017 10:15:00] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[16/May/2017 10:15:03] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/test/ HTTP/1.1" 200 8402
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 304 0
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/teledm/css/base.css HTTP/1.1" 304 0
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/select2/dist/css/select2.min.css HTTP/1.1" 304 0
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/teledm/css/form.css HTTP/1.1" 304 0
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/teledm/css/mapViewer.css HTTP/1.1" 304 0
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/jquery/dist/jquery.js HTTP/1.1" 304 0
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/jquery-ui/jquery-ui.js HTTP/1.1" 304 0
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/jquery.cookie/jquery.cookie.js HTTP/1.1" 304 0
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/moment/min/moment.min.js HTTP/1.1" 304 0
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/select2/dist/js/select2.js HTTP/1.1" 304 0
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/teledm/js/base.js HTTP/1.1" 304 0
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 304 0
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/highcharts-export-csv/export-csv.js HTTP/1.1" 304 0
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/respond/src/respond.js HTTP/1.1" 304 0
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/html5shiv/dist/html5shiv-printshiv.js HTTP/1.1" 304 0
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/teledm/js/test.js HTTP/1.1" 200 6010
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/teledm/images/cnrm.jpeg HTTP/1.1" 304 0
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/teledm/images/image_en_tete.jpeg HTTP/1.1" 304 0
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/teledm/images/cnrs.jpeg HTTP/1.1" 304 0
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/teledm/images/crc.jpeg HTTP/1.1" 304 0
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/teledm/images/ehesp.jpeg HTTP/1.1" 304 0
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/teledm/images/institutPasteur.jpeg HTTP/1.1" 304 0
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/teledm/images/ird.jpeg HTTP/1.1" 304 0
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/teledm/images/ub.jpeg HTTP/1.1" 304 0
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/teledm/images/ulg.jpeg HTTP/1.1" 304 0
[16/May/2017 10:15:03] INFO [django.server:124] "GET /static/teledm/images/uLille1.jpeg HTTP/1.1" 304 0
[16/May/2017 10:15:06] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=270%2C350&TIME=2007-01-02&NUMCOLORBANDS=250&OPACITY=100&BBOX=-77.6,12.4,24.8,114.8&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 6980
[16/May/2017 10:15:06] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=270%2C350&TIME=2007-01-02&NUMCOLORBANDS=250&OPACITY=100&BBOX=-180,-90,-77.6,12.4&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 925
[16/May/2017 10:15:06] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=270%2C350&TIME=2007-01-02&NUMCOLORBANDS=250&OPACITY=100&BBOX=-77.6,-90,24.8,12.4&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 2624
[16/May/2017 10:15:06] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=270%2C350&TIME=2007-01-02&NUMCOLORBANDS=250&OPACITY=100&BBOX=24.8,-90,127.2,12.4&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 2793
[16/May/2017 10:15:06] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=270%2C350&TIME=2007-01-02&NUMCOLORBANDS=250&OPACITY=100&BBOX=24.8,12.4,127.2,114.8&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 4628
[16/May/2017 10:15:06] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=270%2C350&TIME=2007-01-02&NUMCOLORBANDS=250&OPACITY=100&BBOX=-180,12.4,-77.6,114.8&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 925
[16/May/2017 10:15:06] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=270%2C350&TIME=2007-01-02&NUMCOLORBANDS=250&OPACITY=100&BBOX=127.2,-90,229.6,12.4&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 925
[16/May/2017 10:15:06] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/proxywms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&STYLES=boxfill%2Frainbow&COLORSCALERANGE=270%2C350&TIME=2007-01-02&NUMCOLORBANDS=250&OPACITY=100&BBOX=127.2,12.4,229.6,114.8&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 925
[16/May/2017 11:15:53] DEBUG [django.db.backends:91] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[16/May/2017 11:15:53] DEBUG [django.db.backends:91] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[16/May/2017 11:53:56] DEBUG [teledm.views:172] Debug message!
[16/May/2017 11:53:56] INFO [teledm.views:173] Info message!
[16/May/2017 11:53:56] WARNING [teledm.views:174] Warning message!
[16/May/2017 11:53:56] ERROR [teledm.views:175] Error message!
[16/May/2017 11:53:56] CRITICAL [teledm.views:176] Critical message!
[16/May/2017 11:53:56] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 20280
[16/May/2017 11:54:20] DEBUG [teledm.views:172] Debug message!
[16/May/2017 11:54:20] INFO [teledm.views:173] Info message!
[16/May/2017 11:54:20] WARNING [teledm.views:174] Warning message!
[16/May/2017 11:54:20] ERROR [teledm.views:175] Error message!
[16/May/2017 11:54:20] CRITICAL [teledm.views:176] Critical message!
[16/May/2017 11:54:20] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 20280
[16/May/2017 12:00:42] DEBUG [teledm.views:172] Debug message!
[16/May/2017 12:00:42] INFO [teledm.views:173] Info message!
[16/May/2017 12:00:42] WARNING [teledm.views:174] Warning message!
[16/May/2017 12:00:42] ERROR [teledm.views:175] Error message!
[16/May/2017 12:00:42] CRITICAL [teledm.views:176] Critical message!
[16/May/2017 12:00:42] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 20280
[16/May/2017 12:01:22] DEBUG [teledm.views:172] Debug message!
[16/May/2017 12:01:22] INFO [teledm.views:173] Info message!
[16/May/2017 12:01:22] WARNING [teledm.views:174] Warning message!
[16/May/2017 12:01:22] ERROR [teledm.views:175] Error message!
[16/May/2017 12:01:22] CRITICAL [teledm.views:176] Critical message!
[16/May/2017 12:01:22] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 20280
[16/May/2017 12:01:38] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/Catalogues HTTP/1.1" 200 3857
[16/May/2017 12:01:39] INFO [django.server:124] "GET /static/portailCRC/css/home.css HTTP/1.1" 200 480
[16/May/2017 12:01:39] INFO [django.server:124] "GET /static/portailCRC/images/logo_biogeo_72.jpg HTTP/1.1" 200 15505
[16/May/2017 12:01:39] INFO [django.server:124] "GET /static/portailCRC/images/Logo_CRC_transparent.png HTTP/1.1" 200 13653
[16/May/2017 12:01:39] INFO [django.server:124] "GET /static/portailCRC/images/bandeau-labo4.jpg HTTP/1.1" 200 16156
[16/May/2017 12:01:39] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[16/May/2017 12:01:39] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'portailCRC.urls' from '/home/mers/dev/crc/portailCRC/urls.pyc'> (portailCRC:portailCRC) ^climdata.u-bourgogne.fr/Catalogues>"
[16/May/2017 12:01:39] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'teledm.urls' from '/home/mers/dev/crc/teledm/urls.pyc'> (teledm:teledm) ^climdata.u-bourgogne.fr/teledm/>"
[16/May/2017 12:01:39] WARNING [django.request:152] Not Found: /favicon.ico
[16/May/2017 12:01:39] WARNING [django.server:124] "GET /favicon.ico HTTP/1.1" 404 3336
[16/May/2017 12:01:39] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[16/May/2017 12:01:39] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'portailCRC.urls' from '/home/mers/dev/crc/portailCRC/urls.pyc'> (portailCRC:portailCRC) ^climdata.u-bourgogne.fr/Catalogues>"
[16/May/2017 12:01:39] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'teledm.urls' from '/home/mers/dev/crc/teledm/urls.pyc'> (teledm:teledm) ^climdata.u-bourgogne.fr/teledm/>"
[16/May/2017 12:01:39] WARNING [django.request:152] Not Found: /favicon.ico
[16/May/2017 12:01:39] WARNING [django.server:124] "GET /favicon.ico HTTP/1.1" 404 3336
[16/May/2017 12:01:40] DEBUG [teledm.views:119] this is a debug message!
[16/May/2017 12:01:40] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/ HTTP/1.1" 200 8882
[16/May/2017 12:01:40] INFO [django.server:124] "GET /static/teledm/css/base.css HTTP/1.1" 200 859
[16/May/2017 12:01:40] INFO [django.server:124] "GET /static/teledm/css/form.css HTTP/1.1" 200 2271
[16/May/2017 12:01:40] INFO [django.server:124] "GET /static/select2/dist/css/select2.min.css HTTP/1.1" 200 15196
[16/May/2017 12:01:40] INFO [django.server:124] "GET /static/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 200 121200
[16/May/2017 12:01:40] INFO [django.server:124] "GET /static/jquery/dist/jquery.js HTTP/1.1" 200 267194
[16/May/2017 12:01:40] INFO [django.server:124] "GET /static/jquery-ui/jquery-ui.js HTTP/1.1" 200 520714
[16/May/2017 12:01:40] INFO [django.server:124] "GET /static/jquery.cookie/jquery.cookie.js HTTP/1.1" 200 3121
[16/May/2017 12:01:40] INFO [django.server:124] "GET /static/moment/min/moment.min.js HTTP/1.1" 200 61317
[16/May/2017 12:01:40] INFO [django.server:124] "GET /static/teledm/js/home.js HTTP/1.1" 200 364
[16/May/2017 12:01:40] INFO [django.server:124] "GET /static/teledm/js/base.js HTTP/1.1" 200 129
[16/May/2017 12:01:40] INFO [django.server:124] "GET /static/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 200 37045
[16/May/2017 12:01:40] INFO [django.server:124] "GET /static/select2/dist/js/select2.js HTTP/1.1" 200 141934
[16/May/2017 12:01:40] INFO [django.server:124] "GET /static/teledm/images/image_en_tete.jpeg HTTP/1.1" 200 36924
[16/May/2017 12:01:40] INFO [django.server:124] "GET /static/teledm/images/cnrm.jpeg HTTP/1.1" 200 6949
[16/May/2017 12:01:40] INFO [django.server:124] "GET /static/teledm/images/cnrs.jpeg HTTP/1.1" 200 2330
[16/May/2017 12:01:40] INFO [django.server:124] "GET /static/teledm/images/ehesp.jpeg HTTP/1.1" 200 1833
[16/May/2017 12:01:40] INFO [django.server:124] "GET /static/teledm/images/institutPasteur.jpeg HTTP/1.1" 200 3518
[16/May/2017 12:01:40] INFO [django.server:124] "GET /static/teledm/images/crc.jpeg HTTP/1.1" 200 2522
[16/May/2017 12:01:40] INFO [django.server:124] "GET /static/teledm/images/ird.jpeg HTTP/1.1" 200 5127
[16/May/2017 12:01:40] INFO [django.server:124] "GET /static/teledm/images/ub.jpeg HTTP/1.1" 200 3992
[16/May/2017 12:01:40] INFO [django.server:124] "GET /static/teledm/images/ulg.jpeg HTTP/1.1" 200 1587
[16/May/2017 12:01:40] INFO [django.server:124] "GET /static/teledm/images/uLille1.jpeg HTTP/1.1" 200 2347
[16/May/2017 12:01:42] DEBUG [teledm.views:172] Debug message!
[16/May/2017 12:01:42] INFO [teledm.views:173] Info message!
[16/May/2017 12:01:42] WARNING [teledm.views:174] Warning message!
[16/May/2017 12:01:42] ERROR [teledm.views:175] Error message!
[16/May/2017 12:01:42] CRITICAL [teledm.views:176] Critical message!
[16/May/2017 12:01:42] INFO [django.server:124] "GET /climdata.u-bourgogne.fr/teledm/mapViewer/ HTTP/1.1" 200 20280
[16/May/2017 12:01:43] INFO [django.server:124] "GET /static/teledm/css/mapViewer.css HTTP/1.1" 200 921
[16/May/2017 12:01:43] INFO [django.server:124] "GET /static/html5shiv/dist/html5shiv-printshiv.js HTTP/1.1" 200 16268
[16/May/2017 12:01:43] INFO [django.server:124] "GET /static/respond/src/respond.js HTTP/1.1" 200 9754
[16/May/2017 12:01:43] INFO [django.server:124] "GET /static/highcharts-export-csv/export-csv.js HTTP/1.1" 200 11927
[16/May/2017 12:01:43] INFO [django.server:124] "GET /static/teledm/js/mapViewer.js HTTP/1.1" 200 62125
[16/May/2017 12:01:43] INFO [django.server:124] "GET /static/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 18028
[16/May/2017 12:01:44] INFO [django.server:124] "GET /static/teledm/images/pan.png HTTP/1.1" 200 606
[16/May/2017 12:01:44] INFO [django.server:124] "GET /static/teledm/images/zoomIn.png HTTP/1.1" 200 975
[16/May/2017 12:01:44] INFO [django.server:124] "GET /static/teledm/images/info.png HTTP/1.1" 200 1010
